# Generated by Django 4.1.6 on 2026-02-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_prospect_prospectaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='user_agent',
            new_name='prospect_agent',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='user_account',
        ),
    ]
