# Generated by Django 4.1.6 on 2026-02-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_user_agent_prospect_prospect_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='user_code',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
