# Generated by Django 4.1.6 on 2026-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_prospect_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='user_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
