# Generated by Django 4.1.6 on 2026-02-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_prospect_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='code',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
