# Generated by Django 4.1.6 on 2026-02-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_useraccount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
