# Generated by Django 4.1.6 on 2026-02-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_useraccount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='prospect_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
