# Generated by Django 4.1.6 on 2026-02-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_prospect_prospect_id_alter_prospect_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='session_id',
        ),
        migrations.AddField(
            model_name='prospectaction',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
