# Generated by Django 4.1.6 on 2026-02-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_prospect_session_id_prospectaction_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
