# Generated by Django 4.1.6 on 2026-02-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_prospect_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectaction',
            name='ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
