# Generated by Django 4.1.6 on 2026-02-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_prospectaction_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='user_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
