# Generated by Django 4.1.6 on 2026-02-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_prospect_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='prospect_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
