# Generated by Django 4.1.6 on 2026-02-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_prospect_prospect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='path',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
