# Generated by Django 4.1.6 on 2026-02-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_prospect_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='path',
        ),
    ]
