# Generated by Django 5.2.11 on 2026-02-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_prospect_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
