# Generated by Django 5.2.11 on 2026-02-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_prospect_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
