# Generated by Django 5.2.11 on 2026-02-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_update_at_prospect_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='prospect_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
