# Generated by Django 5.2.11 on 2026-02-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_prospect_prospect_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectaction',
            name='ip',
        ),
        migrations.AddField(
            model_name='prospect',
            name='departamento',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
