# Generated by Django 5.2.11 on 2026-02-18 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_prospectaction_ip_prospect_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Enter a valid phone number.')]),
        ),
    ]
