# Generated by Django 5.2.11 on 2026-02-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='refferer_code_used',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
