# Generated by Django 5.2.11 on 2026-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='code',
            field=models.CharField(blank=True, default='5dfda4db-ccc2-4e18-97a3-46c7a410d6de', max_length=40),
        ),
    ]
