# Generated by Django 5.2.11 on 2026-02-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_useraccount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
