# Generated by Django 5.2.11 on 2026-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_useraccount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='plan',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Eureka', 'Eureka')], default='Premium', max_length=9),
        ),
    ]
