# Generated by Django 5.2.11 on 2026-03-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_useraccount_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
