# Generated by Django 5.2.11 on 2026-03-31 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_useraccount_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('initial_video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('presentation_video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('catalog_video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('why_bioliffe_video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_page_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
